# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b7e7c2c566ed330ea38d85fbea7b6f2a70967efdb1931fd6110351e23b80c7ad1818c2fed4ca8da83a25e384c63c7657365cabe7f6f46e26f71c0c7d173bcdd

test:
  secret_key_base: d847ae18d201b0e01e537fd558129f60491212a592963b0abf4ec31ae8a9d0c9a17e686f836603eea8b68d485e64494f223336e6c8b05461383d596edce42cfb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
